name: Run once a day minute

on:
 workflow_dispatch:
 schedule:
    - cron: "1 1 * * *"

jobs:
  cron:
    name: Run once a day minute
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello World"
