name: Secrets Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"
jobs:
  build:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:  
      - name: Echo Environment Variable
        run: echo "$API_CSPROJ_PATH"