name: Secrets Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"
jobs:
  build:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:  
      - name: Echo Environment Variable
        run: echo "$API_CSPROJ_PATH"
      
      - name: Echo Secret to a file
        run: echo "${{ secrets.SECRET_API_KEY }}"   > secret.txt

      - name: Read Secret from File
        run: cat secret.txt
